apiVersion: apps/v1
kind: Deployment
metadata:
  name: okchen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okchen
  template:
    metadata:
      labels:
        app: okchen
    spec:
      containers:
      - image: okteto.dev/okchen:latest
        name: okchen
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "b58e637a-9b13-46e4-83ae-5e4d4975222d"
        - name: Vless_Path
          value: "/awaeo"
        - name: Vmess_UUID
          value: "b58e637a-9b13-46e4-83ae-5e4d4975222d"
        - name: Vmess_Path
          value: "/ea23a"
        - name: Share_Path
          value: "/Share665"
